function plotODF(varargin)

error('%s\n\n%s\n%s\n\n%s\n\n%s',...
  'Using plotODF is obsolete since MTEX 4.1. Use .', ...
  '  plotSection(odf)',...
  '  plotSection(ori)',...
  'instead. For EBSD data use',...
  '  plotSection(ebsd(''phaseName'').orientations)')

end

