function handles = import_gui_kernel(wzrd)
% page for setting specimen symmetry

pos = get(wzrd,'Position');
h = pos(4);
w = pos(3);
ph = 270;

handles = getappdata(wzrd,'handles');

this_page = get_panel(w,h,ph);
handles.pages = [handles.pages,this_page];
setappdata(this_page,'pagename','Set Smoothing Kernel');

set(this_page,'visible','off');

kg = uibuttongroup('title','Smoothing Kernel',...
  'Parent',this_page,...
  'units','pixels','position',[0 0 w-20 h-120]);

%% ODF approximation

handles.exact = uicontrol(...
  'Parent',kg,...
  'Style','check',...
  'String','use ODF approximation',...
  'Value',1,...
  'position',[10 10 250 20]);

uicontrol(...
  'Parent',kg,...
  'Style','text',...
  'String','Resolution',...
  'HitTest','off',...
  'HorizontalAlignment','left',...
  'position',[300 10 100 15]);

handles.approx = uicontrol(...
  'Parent',kg,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','right',...
  'Position',[400 10 40 22],...
  'String','5',...
  'Style','edit');

%% kernel smoothing

uicontrol(...
 'Parent',kg,...
  'String','Kernel',...
  'HitTest','off',...
  'Style','text',...
  'HorizontalAlignment','left',...
  'Position',[10 40 50 15]);

handles.specime = uicontrol(...
  'Parent',kg,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Position',[60 40 220 20],...
  'String',blanks(0),...
  'Style','popup',...
  'String',kernel('names'),...
  'Value',1);

uicontrol(...
 'Parent',kg,...
  'String','Halfwidth',...
  'HitTest','off',...
  'Style','text',...
  'HorizontalAlignment','left',...
  'Position',[300 40 90 15]);

handles.halfwidth = uicontrol(...
  'Parent',kg,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','right',...
  'Position',[400 40 40 22],...
  'String','5',...
  'Style','edit');

%% kernel plot

handles.kernelAxis = axes(...
  'Parent',kg,...
  'Units','pixels',...
  'Position',[20 90 w-60 h-240],...
  'yTick',[],...
  'box','on');

setappdata(this_page,'goto_callback',@goto_callback);
setappdata(this_page,'leave_callback',@leave_callback);
setappdata(wzrd,'handles',handles);


%% -------------- Callbacks ---------------------------------

function goto_callback(varargin)

get_ss(gcbf);
handles = getappdata(gcbf,'handles');

plot_options = get_mtex_option('default_plot_options');
value = get_option(plot_options,'rotate',0);
 
direction = 1+mod(round(2*(value) / pi),4);
   
set(handles.plot_dir(direction),'value',1);
set(handles.plot_dir(1:4 ~= direction),'value',0);

% plot_options = get_mtex_option('default_plot_options');
% if check_option(plot_options,'rotate')
%   set(handles.plot_rotate,'value',1);
%   set(handles.plot_rotateAngle,'string',int2str(get_option(plot_options,'rotate',0)/degree));
% else
%   set(handles.plot_rotate,'value',0);
% end
% 
% if check_option(plot_options,'fliplr'), set(handles.plot_fliplr,'value',1);end
% if check_option(plot_options,'flipud'), set(handles.plot_flipud,'value',1);end

%  set(handles.comment,'String',get(appdata.data,'comment'));


function leave_callback(varargin)

set_ss(gcbf);
handles = getappdata(gcbf,'handles');

plot_options = get_mtex_option('default_plot_options');
plot_options = set_option(plot_options,'rotate',...
     (find(cell2mat(get(handles.plot_dir,'value')))-1)*pi/2);
set_mtex_option('default_plot_options',plot_options);

% plot_options = get_mtex_option('default_plot_options');
% if get(handles.plot_rotate,'value')
%   plot_options = set_option(plot_options,'rotate',...
%     str2double(get(handles.plot_rotateAngle,'string'))*degree);
% else
%   plot_options = delete_option(plot_options,'rotate');
% end
% if get(handles.plot_flipud,'value')
%   plot_options = set_option(plot_options,'flipud');
% else
%   plot_options = delete_option(plot_options,'flipud',0);
% end

% if get(handles.plot_fliplr,'value')
%   plot_options = set_option(plot_options,'fliplr');
% else
%   plot_options = delete_option(plot_options,'fliplr',0);
% end
% 
% 
% set_mtex_option('default_plot_options',plot_options);
%set(appdata.data,'comment',get(handles.comment,'String'));


%% ------------- Private Functions ------------------------------------------------

function set_ss(wzrd)
% set specimen symmetry

handles = getappdata(wzrd,'handles');
data = getappdata(wzrd,'data');

ss = symmetries(get(handles.specime,'Value'));
ss = strtrim(ss{1}(1:6));
ss = symmetry(ss);

% set data
data = set(data,'SS',ss);
setappdata(wzrd,'data',data);


function get_ss(wzrd)
% write ss to page

handles = getappdata(wzrd,'handles');
data = getappdata(wzrd,'data');

% get ss
ss = get(data,'SS');

% set specimen symmetry
ssname = strmatch(Laue(ss),symmetries);
set(handles.specime,'value',ssname(1));
 
 
%% ----------------------------------------------------------

% nv = uibuttongroup('title','Negative Values',...
%   'Parent',this_page,...
%   'units','pixels','position',[0 ph-210 380 100]);
% 
% uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','keep negative values',...
%   'Value',1,...
%   'position',[10 60 160 20]);
% 
% handles.dnv = uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','delete negative values',...
%   'Value',0,...
%   'position',[10 35 160 20]);
% 
% handles.setnv = uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','set negative values to',...
%   'Value',0,...
%   'position',[10 10 160 20]);
% 
% handles.rnv = uicontrol(...
%   'Parent',nv,...
%   'BackgroundColor',[1 1 1],...
%   'FontName','monospaced',...
%   'HorizontalAlignment','right',...
%   'Position',[190 8 80 25],...
%   'String','0',...
%   'Style','edit');
% 
% 
% co = uibuttongroup('title','Comment',...
%   'Parent',this_page,...
%   'units','pixels','position',[0 0 380 54]);
% 
% handles.comment = uicontrol(...
%   'Parent',co,...
%   'BackgroundColor',[1 1 1],...
%   'FontName','monospaced',...
%   'HorizontalAlignment','left',...
%   'Position',[10 8 360 25],...
%   'String',blanks(0),...
%   'Style','edit');
