function handles = import_gui_generic( handles, varargin )

pos = get(handles.wzrd,'Position');
h = pos(4);
w = pos(3);

type = get_option(varargin,'type');


%% page title
handles.name = uicontrol(...
'Parent',handles.wzrd,...
 'FontSize',12,...
 'ForegroundColor',[0.3 0.3 0.3],...
 'FontWeight','bold',...
 'BackgroundColor',[1 1 1],...
 'HorizontalAlignment','left',...
 'Position',[10 h-37 w-150 20],...
 'Style','text',...
 'HandleVisibility','off',...
 'HitTest','off');

%% navigation
handles.next = uicontrol(...
  'Parent',handles.wzrd,...
  'String','Next >>',...
  'CallBack','import_wizard(''page_next'')',...
  'Position',[w-30-80*2 10 80 25]);

handles.prev = uicontrol(...
  'Parent',handles.wzrd,...
  'String','<< Previous',...
  'CallBack','import_wizard(''page_prev'')',...
  'Position',[w-30-80*3 10 80 25]);

handles.finish = uicontrol(...
  'Parent',handles.wzrd,...
  'String','Finish',...
  'Enable','off',...
  'CallBack',['import_wizard_' type '(''finish'')'],...
  'Position',[w-90 10 80 25]);

handles.plot = uicontrol(...
  'Parent',handles.wzrd,...
  'String','Plot',...
  'CallBack',['import_wizard_' type '(''plot_' type ''')'],...
  'Position',[10 10 80 25],...
  'Visible','off');

uipanel(...
  'units','pixel',...
  'HighlightColor',[0 0 0],...
  'Position',[10 50 w-20 1]);