function handles = import_gui_xrdml( handles, varargin )

pos = get(handles.xrdml_frame,'Position');
h = pos(4);
w = pos(3);

ph = 300;

%%
descriptor ={'Texture pole figure',...
  'Texture background measurement',...
  'Texture defocusing measurement',...
  'Texture defocusing background measurement'};

%%
for i=1:4 
uicontrol('Style','Text',...
  'FontWeight','bold',...
  'HorizontalAlignment','left',...
  'Position',[20*(8*i-7) ph 150 30],...
  'string',descriptor{i});
handles.list{i} = uicontrol(...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Max',2,...
  'Position',[-140+160*i 70 150 ph-110],...
  'String',blanks(0),...
  'Style','listbox',...
  'Value',1);
handles.addt = uicontrol(...
  'String','Add File',...
  'Callback',['xrdml_help(','''add'',','''',i,'''',')'],...
  'Position',[-140+160*i ph-35 75 25]);
handles.delt = uicontrol(...
  'String','Remove File',...
  'CallBack',['xrdml_help(','''del'',','''',i,'''',')'],...
  'Position',[-65+160*i ph-35 75 25]);
end

%%
handles.proceed = uicontrol('Style','PushButton','String','Proceed ',...
  'Position',[w-90,10,70,25],'CallBack','xrdml_help(''finish'')');

handles.cancel = uicontrol('Style','PushButton','String','Cancel ',...
  'Position',[w-160,10,70,25],'CallBack','xrdml_help(''cancel'')');

uipanel('units','pixel',...
  'HighlightColor',[0 0 0],...
  'Position',[10 50 w-20 1]);
