function import_gui_finish(wzrd)
% final import wizard page

pos = get(wzrd,'Position');
h = pos(4);
w = pos(3);
ph = 270;

this_page = get_panel(w,h,ph);
handles = getappdata(wzrd,'handles');
handles.pages = [handles.pages,this_page];
setappdata(this_page,'pagename','Summary');

set(this_page,'visible','off');
 
uicontrol('Parent',this_page,...
  'String','EBSD Data summary:',...
  'Position',[10 ph-30 w-40 20 ],...
  'Style','text',...
  'HorizontalAlignment','left');


handles.preview = uicontrol(...
  'Parent',this_page,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Max',2,...
  'Position',[10 ph-105 w-40 80 ],...
  'String',blanks(0),...
  'Style','edit');
  
handles.templatetip = uicontrol('Parent',this_page,...
  'String','Template:',...
  'Position',[10 ph-140 w-40 20 ],...
  'Style','text',...
  'HorizontalAlignment','left');

handles.template = uicontrol(...
  'Parent',this_page,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Max',2,...
  'Position',[10 10 w-40 125 ],...
  'String',blanks(0),...
  'Style','listbox');%,... 

setappdata(this_page,'goto_callback',@goto_callback);
setappdata(this_page,'leave_callback',@leave_callback);
setappdata(wzrd,'handles',handles);


%% --------------- Callbacks -------------------------------------

function goto_callback(varargin)

handles = getappdata(gcbf,'handles');
data = getappdata(gcbf,'data');

str = char(data);
set(handles.preview,'String',str(:,1:min(end,54)));


set(handles.templatetip,'String', ['Select ' class(data) ' Templates:']);

  % find some other templates 
templates = dir( fullfile(mtex_path,'templates',[ class(data) '_*.m']) );
templates = {templates.name};
templ = regexprep(templates,[ class(data) '_(\w*).m'],'$1');
templ = ['->Export Variable to Workspace', templ, 'Look for new Templates Online'];

set(handles.template,'String',templ);
set(handles.template,'Value',[1]);
setappdata(gcbf,'templates',templates);

function leave_callback(varargin)

