function handles = import_gui_ss(wzrd)
% page for setting specimen symmetry

pos = get(wzrd,'Position');
h = pos(4);
w = pos(3);
ph = 270;

handles = getappdata(wzrd,'handles');

this_page = get_panel(w,h,ph);
handles.pages = [handles.pages,this_page];
setappdata(this_page,'pagename','Set Specimen Geometry');

set(this_page,'visible','off');

scs = uibuttongroup('title','Specimen Coordinate System',...
  'Parent',this_page,...
  'units','pixels','position',[0 ph-175 w-20 170]);


uicontrol(...
 'Parent',scs,...
  'String','specimen symmetry:',...
  'HitTest','off',...
  'Style','text',...
  'HorizontalAlignment','left',...
  'Position',[10 120  150 15]);

handles.specime = uicontrol(...
  'Parent',scs,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Position',[160 120 170 20],...
  'String',blanks(0),...
  'Style','popup',...
  'String',symmetries(1:3),...
  'Value',1);


handles.rotate = uicontrol(...
  'Parent',scs,...
  'Style','check',...
  'String','rotate around z-axis by ',...
  'Value',0,...
  'position',[10 80 180 20]);

handles.rotateAngle = uicontrol(...
  'Parent',scs,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','right',...
  'Position',[190 78 30 25],...
  'String','0',...
  'Style','edit');

uicontrol(...
  'Parent',scs,...
  'String','degree',...
  'HitTest','off',...
  'Style','text',...
  'HorizontalAlignment','left',...
  'Position',[230 78 50 20]);

handles.flipud = uicontrol(...
  'Parent',scs,...
  'Style','check',...
  'String','flip z-axis',...
  'Value',0,...
  'position',[300 80 160 20]);

handles.euler2spatial = uicontrol(...
  'Parent',scs,...
  'Style','radio',...
  'String','keep Euler angles and spatial coordinates',...
  'Value',0,...
  'position',[10 54 400 20]);

handles.euler2spatial = uicontrol(...
  'Parent',scs,...
  'Style','radio',...
  'String','convert Euler angle to spatial reference frame',...
  'Value',0,...
  'position',[10 32 400 20]);

handles.spatial2euler= uicontrol(...
  'Parent',scs,...
  'Style','radio',...
  'String','convert spatial coordinates to Euler reference frame',...
  'Value',0,...
  'position',[10 10 400 20]);

% uicontrol(...
%   'String',['Use the plot command', ...
%    'to verify that the specimen coordinate' ...
%    ' system is aligned properly to the data!'],...
%   'Parent',this_page,...
%   'HitTest','off',...
%   'Style','text',...
%   'HorizontalAlignment','left',...
%   'Position',[5 0 390 30]);

plotg = uibuttongroup('title','MTEX Plotting Convention',...
  'Parent',this_page,...
  'units','pixels','position',[0 1 w-20 80]);

handles.xyz(1) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('1xyz.png'),...
  'TooltipString','add data file',...
  'Position',[5 5 54 54]);

handles.xyz(2) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('2xyz.png'),...
  'TooltipString','add data file',...
  'Position',[64 5 54 54]);

handles.xyz(3) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('3xyz.png'),...
  'TooltipString','add data file',...
  'Position',[123 5 54 54]);

handles.xyz(4) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('4xyz.png'),...
  'TooltipString','add data file',...
  'Position',[182 5 54 54]);

handles.xyz(5) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('1yxz.png'),...
  'TooltipString','add data file',...
  'Position',[241 5 54 54]);

handles.xyz(6) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('4yxz.png'),...
  'TooltipString','add data file',...
  'Position',[300 5 54 54]);

handles.xyz(7) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('3xyz.png'),...
  'TooltipString','add data file',...
  'Position',[359 5 54 54]);

handles.xyz(8) = uicontrol(...
  'parent',plotg,...
  'style','togglebutton',...
  'cdata',loadpng('2yxz.png'),...
  'TooltipString','add data file',...
  'Position',[418 5 54 54]);

setappdata(this_page,'goto_callback',@goto_callback);
setappdata(this_page,'leave_callback',@leave_callback);
setappdata(wzrd,'handles',handles);


%% -------------- Callbacks ---------------------------------

function goto_callback(varargin)

% set specimen symmetry 
get_ss(gcbf);

% set xyz convention
xaxis = NWSE(getpref('mtex','xAxisDirection'));
zaxis = UpDown(getpref('mtex','zAxisDirection'));
direction = xaxis + 4*(zaxis-1);

handles = getappdata(gcbf,'handles');
set(handles.xyz(direction),'value',1);
set(handles.xyz(1:8 ~= direction),'value',0);


function leave_callback(varargin)

set_ss(gcbf);

handles = getappdata(gcbf,'handles');

% get xyz convention
direction = find(cell2mat(get(handles.xyz,'value')));

xaxis = 1 + mod(direction-1,4);
zaxis = 1 + (direction > 4);

setpref('mtex','xAxisDirection',NWSE(xaxis));
setpref('mtex','zAxisDirection',UpDown(zaxis));


%% ------------- Private Functions ------------------------------------------------

function set_ss(wzrd)
% set specimen symmetry

handles = getappdata(wzrd,'handles');
data = getappdata(wzrd,'data');

ss = symmetries(get(handles.specime,'Value'));
ss = strtrim(ss{1}(1:6));
ss = symmetry(ss);

% set data
data = set(data,'SS',ss);
setappdata(wzrd,'data',data);


function get_ss(wzrd)
% write ss to page

handles = getappdata(wzrd,'handles');
data = getappdata(wzrd,'data');

% get ss
ss = get(data,'SS');

% set specimen symmetry
ssname = strmatch(Laue(ss),symmetries);
set(handles.specime,'value',ssname(1));

% set alignment of the plotting coordinate system


%% ----------------------------------------------------------

% nv = uibuttongroup('title','Negative Values',...
%   'Parent',this_page,...
%   'units','pixels','position',[0 ph-210 380 100]);
%
% uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','keep negative values',...
%   'Value',1,...
%   'position',[10 60 160 20]);
%
% handles.dnv = uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','delete negative values',...
%   'Value',0,...
%   'position',[10 35 160 20]);
%
% handles.setnv = uicontrol(...
%   'Parent',nv,...
%   'Style','radi',...
%   'String','set negative values to',...
%   'Value',0,...
%   'position',[10 10 160 20]);
%
% handles.rnv = uicontrol(...
%   'Parent',nv,...
%   'BackgroundColor',[1 1 1],...
%   'FontName','monospaced',...
%   'HorizontalAlignment','right',...
%   'Position',[190 8 80 25],...
%   'String','0',...
%   'Style','edit');
%
%
% co = uibuttongroup('title','Comment',...
%   'Parent',this_page,...
%   'units','pixels','position',[0 0 380 54]);
%
% handles.comment = uicontrol(...
%   'Parent',co,...
%   'BackgroundColor',[1 1 1],...
%   'FontName','monospaced',...
%   'HorizontalAlignment','left',...
%   'Position',[10 8 360 25],...
%   'String',blanks(0),...
%   'Style','edit');

function cdata = loadpng(fname)

[cdata,map,alpha] = imread(fullfile(mtex_path,'help','general',fname)); %#ok<ASGLU>
%cdata = ind2rgb( cdata, map )

alpha = double(alpha);
alpha(alpha==0) = NaN;
cdata = repmat(alpha,[1,1,3]);
cdata = 1-(cdata+150)./(255+150);

