function handles = import_gui_options( handles )

pos = get(handles.wzrd,'Position');
h = pos(4);
w = pos(3);

ph = 270;


%% page 4
handles.page4 = get_panel(w,h,ph);
set(handles.page4,'visible','off');

scs = uibuttongroup('title','Specimen Coordinate System',...
  'Parent',handles.page4,...
  'Visible','off',...
  'units','pixels','position',[0 ph-120 380 110]);


handles.rotate = uicontrol(...
  'Parent',scs,...
  'Style','check',...
  'String','rotate around z-axis by ',...
  'Value',1,...
  'Visible','off',...
  'position',[10 60 180 20]);

handles.rotateAngle = uicontrol(...
  'Parent',scs,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','right',...
  'Position',[190 58 80 25],...
  'String','0',...
  'Visible','off',...
  'Style','edit');

uicontrol(...
  'Parent',scs,...
  'String','degree',...
  'HitTest','off',...
  'Style','text',...
  'HorizontalAlignment','left',...
  'Visible','off',...
  'Position',[280 55 50 20]);

handles.flipud = uicontrol(...
  'Parent',scs,...
  'Style','check',...
  'String','flip upside down',...
  'Value',1,...
  'Visible','off',...
  'position',[10 35 160 20]);

handles.fliplr = uicontrol(...
  'Parent',scs,...
  'Style','check',...
  'String','flip left to right',...
  'Value',0,...
  'Visible','off',...
  'position',[10 10 160 20]);

nv = uibuttongroup('title','Negative Values',...
  'Parent',handles.page4,...
  'Visible','off',...
  'units','pixels','position',[0 ph-210 380 80]);

handles.inv = uicontrol(...
  'Parent',nv,...
  'Style','radio',...
  'String','ignore negative values',...
  'Value',0,...
  'Visible','off',...
  'position',[10 35 160 20]);

handles.setnv = uicontrol(...
  'Parent',nv,...
  'Style','radio',...
  'String','set negative values to',...
  'Value',0,...
  'Visible','off',...
  'position',[10 10 160 20]);

handles.rnv = uicontrol(...
  'Parent',nv,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','right',...
  'Position',[190 8 80 25],...
  'String','0',...
  'Visible','off',...
  'Style','edit');


co = uibuttongroup('title','Comment',...
  'Parent',handles.page4,...
  'Visible','off',...
  'units','pixels','position',[0 0 380 54]);

handles.comment = uicontrol(...
  'Parent',co,...
  'BackgroundColor',[1 1 1],...
  'FontName','monospaced',...
  'HorizontalAlignment','left',...
  'Position',[10 8 360 25],...
  'String',blanks(0),...
  'Visible','off',...
  'Style','edit');
