function [ filter ] = mtexfilefilter( varargin )

switch get_option(varargin,'type','PoleFigure','char')
  case 'PoleFigure'
    filter = {...
      '*','All files';...
      '*.exp','Aachen (.exp)';...
      '*.xp*','BearTex (.xpa,.xpf,.xpe)';...
      '*.cnv;*.cns','dubna (.cnv,.cns)';...
      '*.dat','geesthacht (*.dat)';...
      '*.ptx;*.cpf;*.rpf','heilbronner (*.ptx, *.cpf, *.rpf)';...
      '*.hem','juelich (*.hem)';...
      '*.txt','ascii (*.txt)';...
      '*.txt','philips (*.txt)';...
      '*.ptx;*.dat','ptx (*.dat, *.ptx)';...
      '*.PTX','trullenque (*.PTX)'};
  case 'EBSD'
    filter = {'*','All files';...
      '*.ang','tsl files';...
      '*.ctf','hkl files';...
      '*.txt','ascii files'};
end
