function pageCS(api,phaseNumber)



gui = localCreatePage();

api.setWizardTitle('Crystal Reference Frame');
api.setWizardDescription('Crystal Symmetry')

api.Progress.enableNext(true);

api.setLeavePageCallback(@leavePage);
api.setGotoPageCallback(@gotoPage);


nPhases = 0;
if nargin > 1
  currentPhase = phaseNumber;
else
  currentPhase = 1;
end


CS = 'not available';


% set callbacks
set(gui.hColor    ,'Callback',@localUpdateCS);
set(gui.hCrystal  ,'Callback',@localUpdateCS);
set(gui.hMGroup   ,'SelectionChangeFcn',@localUpdateCS);
set(gui.hCSGroup  ,'SelectionChangeFcn',@localUpdateCS);

% set(gui.hSearchCIF,'CallBack',@lookup_mineral);


  function nextPage = leavePage()
    
    if nPhases > currentPhase
      nextPage = @(api) pageCS(api,currentPhase+1);
    else
      nextPage = @pageSS;
    end
    
  end

  function gotoPage
    
    data = api.getData();
    data = data{1};
    
    
    if isa(data,'EBSD')
      
      CS = get(data,'CSCell');
      nPhases = numel(CS);
      
      CS = CS{currentPhase};
      
      phaseMap = get(data,'phaseMap');
      api.setWizardTitle(['Crystal Reference Frame for Phase '  num2str(phaseMap(currentPhase))]);
      
    else
      
      CS = get(data,'CS');
      nPhases = 1;
      
    end
    
    localReadCS();
    
  end

  function localReadCS()
    
    if ischar(CS)
      
      set(gui.hIndexed(1),'Value',0);
      set(gui.hIndexed(2),'Value',1);
      
      set(gui.hCS,'Enable','off');
      set(gui.hMineral,'Enable','off');
      set(gui.hColor,'Enable','off');
      
      set(gui.hMineral,'string',CS);
      
    else
      
      set(gui.hMineral,'enable','on');
      set(gui.hColor,'enable','on');
      set(gui.hCS,'enable','on');
      
      set(gui.hIndexed(1),'Value',1);
      set(gui.hIndexed(2),'Value',0);
      
      csname = strmatch(Laue(CS),SymmetryList);
      set(gui.hCrystal,'value',csname(1));
      
      color = get(CS,'color');
      color = strmatch(color,getMTEXpref('EBSDColorNames'));
      set(gui.hColor,'value',color(1));
      
      
      % set alignment
      al = [get(CS,'alignment'),{'',''}];
      set(gui.hAlignment(1),'value',find(strcmp(AlignmentList,al{1})));
      set(gui.hAlignment(2),'value',find(strcmp(AlignmentList,al{2})));
      
      % set axes
      [c, angle] = get_axisangel(CS);
      
      for k=1:3
        set(gui.hAxes(k),'String',c(k));
        set(gui.hAngle(k),'String',angle{k});
      end
      
      % set whether axes and angles can be changed
      if ~strcmp(Laue(CS),{'-1','2/m'})
        set(gui.hAngle, 'Enable', 'off');
      end
      
      % set mineral
      set(gui.hMineral,'string',get(CS,'mineral'));
    end
    
  end

  function localUpdateCS(source,event)
    
    
    in = find([get(gui.hIndexed(1),'value') get(gui.hIndexed(2),'value')]);
    
    if in > 1
      
      CS = 'notIndexed';
      
    else
      
      cs = get(gui.hCrystal,'Value');
      cs = SymmetryList(cs);
      cs = strtrim(cs{1}(1:6));
      
      for k=1:3
        axis{k}  =  str2double(get(gui.hAxes(k),'String')); %#ok<AGROW>
        angle{k} =  str2double(get(gui.hAngle(k),'String')); %#ok<AGROW>
      end
      
      mineral = get(gui.hMineral,'string');
      
      al1 = get(gui.hAlignment(1),'Value');
      al2 = get(gui.hAlignment(2),'Value');
      al = AlignmentList;
      
      co = getMTEXpref('EBSDColorNames');
      co = co{get(gui.hColor,'Value')};
      try
        CS = symmetry(cs,[axis{:}],[angle{:}]*degree,al{al1},al{al2},...
          'mineral',mineral,'color',co);
      catch %#ok<CTCH>
        CS = symmetry(cs,[axis{:}],[angle{:}]*degree,'mineral',mineral,'color',co);
      end
    end
    
    
    % update data
    data = api.getData();
    
    for k=1:numel(data)
      
      if isa(data{k},'EBSD')
        
        CSCell = get(data{k},'CSCell');
        CSCell{currentPhase} = CS;
        data{k} = set(data{k},'CS',CSCell);
        
      else
        
        data{k} = set(data{k},'CS',CS);
        
      end
      
      
    end
    
    api.setData(data);
    
    localReadCS();
    
  end

  function [ sym ] = SymmetryList( index )
    
    sym = [ ...
      {'-1    triclinic'}; ...
      {'2/m   monoclinic'};...
      {'mmm   orthorhombic'};...
      {'4/m   tetragonal'};...
      {'4/mmm tetragonal'};...
      {'-3    trigonal'};...
      {'-3m   trigonal'};...
      {'6/m   hexagonal'};...
      {'6/mmm hexagonal'};...
      {'m-3   cubic'};...
      {'m-3m  cubic'}];
    
    if nargin > 0
      sym = sym( index );
    end
    
  end

  function al = AlignmentList
    
    xyz = {'X','Y','Z'};
    abc = {'a','b','c','a*','b*','c*'};
    
    al = {};
    for ix = 1:3
      al = [al cellfun(@(a) [xyz{ix},'||',a],abc,'UniformOutput',false)]; %#ok<AGROW>
    end
    al = [{''} al];
    
  end

  function gui = localCreatePage()
    
    page = api.hPanel;
    
    w = api.Spacings.PageWidth;
    h = api.Spacings.PageHeight;
    m = api.Spacings.Margin;
    
    
    mineralGroup = uibuttongroup('title','Mineral',...
      'Parent',page,...
      'units','pixels','position',[1 h-115 w 115]);
    
    
    indexed(1) = uicontrol(...
      'Parent',mineralGroup,...
      'String','Indexed',...
      'Style','radio',...
      'Position',[10 75 150 15]);
    
    indexed(2) = uicontrol(...
      'Parent',mineralGroup,...
      'String','Not Indexed',...
      'Style','radio',...
      'Position',[95 75 150 15]);
    
    
    uicontrol(...
      'Parent',mineralGroup,...
      'String','mineral name',...
      'HitTest','off',...
      'Style','text',...
      'HorizontalAlignment','left',...
      'Position',[10 45 100 15]);
    
    
    mineral = uicontrol(...
      'Style','edit',...
      'Parent',mineralGroup,...
      'BackgroundColor',[1 1 1],...
      'Position',[110 45 180 20],...
      'HorizontalAlignment','left',...
      'string','');
    
    uicontrol(...
      'Parent',mineralGroup,...
      'String','plotting color',...
      'HitTest','off',...
      'Style','text',...
      'HorizontalAlignment','left',...
      'Position',[10 15 130 15]);
    
    color = uicontrol(...
      'Parent',mineralGroup,...
      'BackgroundColor',[1 1 1],...
      'FontName','monospaced',...
      'HorizontalAlignment','left',...
      'Position',[110 15 180 20],...
      'String',blanks(0),...
      'Style','popup',...
      'String',getMTEXpref('EBSDColorNames'),...
      'Value',1);
    
    look = uicontrol(...
      'Parent',mineralGroup,...
      'String','Load Cif File',...
      'Position',[350 37 100 25]);
    
    
    csGroup = uibuttongroup('title','Crystal Coordinate System',...
      'Parent',page,...
      'units','pixels','position',[1 h-115-135-m w 135],...
      'SelectionChangeFcn',@localUpdateCS);
    
    %     handles.csframe = cs;
    
    uicontrol(...
      'Parent',csGroup,...
      'String','Laue Group',...
      'HitTest','off',...
      'Style','text',...
      'HorizontalAlignment','left',...
      'Position',[10 85 80 15]);
    
    crystal = uicontrol(...
      'Parent',csGroup,...
      'BackgroundColor',[1 1 1],...
      'FontName','monospaced',...
      'HorizontalAlignment','left',...
      'Position',[95 85 180 20],...
      'String',blanks(0),...
      'Style','popup',...
      'String',SymmetryList,...
      'Value',1);
    
    axis_alignment(1) = uicontrol(...
      'Parent',csGroup,...
      'BackgroundColor',[1 1 1],...
      'FontName','monospaced',...
      'HorizontalAlignment','left',...
      'Position',[290 85 80 20],...
      'String',blanks(0),...
      'Style','popup',...
      'String',AlignmentList,...
      'Value',1);
    
    axis_alignment(2) = uicontrol(...
      'Parent',csGroup,...
      'BackgroundColor',[1 1 1],...
      'FontName','monospaced',...
      'HorizontalAlignment','left',...
      'Position',[385 85 80 20],...
      'String',blanks(0),...
      'Style','popup',...
      'String',AlignmentList,...
      'Value',1);
    
    uicontrol(...
      'Parent',csGroup,...
      'String','Axis Length',...
      'HitTest','off',...
      'Style','text',...
      'HorizontalAlignment','left',...
      'Position',[10 50 100 15]);
    uicontrol(...
      'Parent',csGroup,...
      'String','Axis Angle',...
      'HitTest','off',...
      'Style','text',...
      'HorizontalAlignment','left',...
      'Position',[10 15 100 15]);
    
    axis = {'a','b','c'};
    angle=  {'alpha', 'beta', 'gamma'};
    for k=1:3
      uicontrol(...
        'Parent',csGroup,...
        'String',axis{k},...
        'HitTest','off',...
        'Style','text',...
        'HorizontalAlignment','right',...
        'Position',[130+120*(k-1) 50 30 15]);
      uicontrol(...
        'Parent',csGroup,...
        'String',angle{k},...
        'HitTest','off',...
        'Style','text',...
        'HorizontalAlignment','right',...
        'Position',[110+120*(k-1) 15 50 15]);
      ax(k) = uicontrol(...
        'Parent',csGroup,...
        'BackgroundColor',[1 1 1],...
        'FontName','monospaced',...
        'HorizontalAlignment','left',...
        'Position',[165+120*(k-1) 45 60 25],...
        'String',blanks(0),...
        'Style','edit');
      an(k) = uicontrol(...
        'Parent',csGroup,...
        'BackgroundColor',[1 1 1],...
        'FontName','monospaced',...
        'HorizontalAlignment','left',...
        'Position',[165+120*(k-1) 10 60 25],...
        'String',blanks(0),...
        'Style','edit');
    end
    
    gui.hMineral   = mineral;
    gui.hIndexed   = indexed;
    gui.hColor     = color;
    gui.hCrystal   = crystal;
    gui.hAlignment = axis_alignment;
    gui.hAxes      = ax;
    gui.hAngle     = an;
    gui.hSearchCIF = look;
    
    gui.hMGroup    = mineralGroup;
    gui.hCSGroup   = csGroup;
    gui.hCS = [crystal axis_alignment ax an];
    
  end


end