%% EBSD Data Analysis
% This sections gives you an overview over the functionality MTEX offers to
% analyze EBSD data.
%
%
%% Import of EBSD Data
%
% The most comfortable way to import EBSD data into MTEX is to use
% the import wizard, which can be started by the command

import_wizard

%%
% If the data are in a format supported by MTEX the import wizard generates
% a script which imports the data. More information about the import wizard
% and a list of supported file formats can be found
% [[interfacesEBSD_index.html,here]]. A typical script generated by the import 
% wizard looks a follows.


cs = [... % crystal symmetry  for each phase
  symmetry('m-3m'),...
  symmetry('m-3m'),...
  symmetry('m-3m')];

ss = symmetry('-1');  % specimen symmetry

% file name
fname = [mtexDataPath '/aachen_ebsd/85_829grad_07_09_06.txt'];

% load the data
ebsd = loadEBSD(fname,cs,ss,'interface','generic', 'Bunge', ...
  'layout', [5 6 7], 'Phase', 2, 'xy', [3 4], ...
  'ColumnNames', { 'Index' 'MAD' 'BC' 'BS' 'Bands' 'Error' 'RI' } , ...
  'ColumnIndex', [1 8 9 10 11 12 13]);

%%
% 'layout' specifies the columns of orientation data, and 'Phase' the
% column of phase. However, EBSD data often comes along with more 
% information, i.R. with the location of measured orientation at 'xy', and
% additional properties of the Kikuchi patterns and beam diffraction, which
% can be specified by 'ColumnNames' and its corresponding 'ColumnIndex'.


%% Plotting EBSD Data
%
% EBSD data are plotted using the [[EBSD_plot.html,plot]] command.
% It asign a color to each orientation and plots a map of these colors.
% There are several options to specify the way the colors are assigned.

figure('position',[100 100 600 300])
plot(ebsd)

%% Modify EBSD Data
%
% MTEX offers a lot of operations to analyze and manipulate EBSD data, e.g.
%
% * plot pole figures of EBSD data
% * rotate EBSD data
% * find outliers
% * remove specific measurements
% * combine EBSD data from several meassurements
% * compute an ODF
%
% An exhausive introduction how to analyze and modify EBSD data can be found
% <EBSDModification.html here>

%% Calculate an ODF from EBSD Data
%
% The command [[EBSD_calcODF.html,calcODF]]  performs an ODF calculation
% from EBSD data using kernel density estimation EBSD data. For a precise
% explaination of the algorithm and the available options look
% <EBSD2ODFestimation.html here>. 

odf = calcODF(ebsd,'halfwidth',10*degree)
plotpdf(odf,Miller(1,0,0,cs),'reduced')


%% Simulate EBSD Data
%
% Simulating EBSD data from a given ODF has been proven to be
% usefull to analyze the stability of the ODF estimation process. There is
% an <EBSDSimulation.html example> demostrating how to determine the
% number of individuel orientation measurements to estimate the ODF up to a
% given error. The MTEX command to simulate EBSD data is
% <ODF_simulateEBSD.html simulateEBSD>, e.g.

ebsd = simulateEBSD(unimodalODF(idquaternion,cs(1),ss),500)
plotpdf(ebsd,Miller(1,0,0),'reduced','MarkerSize',3)

%% Demo
%
% For a more exausive description of the EBSD class have a look at the 
% [[ebsd_demo.html,EBSD demo]]!
% 
