%% Symmetric spherical functions
%
% A symmetric spherical function has the same scalar value at directions
% related by a point group. Inverse pole figures and directional
% properties of a single crystal are common examples. MTEX represents a
% harmonic function with this constraint as
% <S2FunHarmonicSym.S2FunHarmonicSym.html |S2FunHarmonicSym|>.
%
% Symmetry is the point group under which the data is invariant. It is
% attached to a reference frame rather than being a reference frame
% itself. Use a @specimenSymmetry for directions in the specimen frame and
% a @crystalSymmetry for directions in a crystal frame.

plottingConvention.default('y↑→x');

%% Attach and enforce a symmetry
%
% Start with an ordinary harmonic spherical function. The asymmetric
% smiley makes the effect of symmetrisation easy to see.

sF = S2Fun.smiley;

%%
% Choose orthorhombic specimen symmetry. Passing |sF.how2plot| preserves
% the plotting convention of the function when the symmetry creates its
% reference frame.

ss = specimenSymmetry('222',sF.how2plot);

%%
% For an existing harmonic function, the constructor first attaches the
% symmetry and its frame. It does not yet change the coefficients. The
% subsequent <S2FunHarmonic.symmetrise.html |symmetrise|> call averages
% symmetry-related directions and enforces the constraint.

sFs1 = S2FunHarmonicSym(sF,ss);
sFs1 = sFs1.symmetrise;

%% Plot the fundamental sector
%
% A symmetric function is plotted only in a representative sector by
% default, as is usual for an inverse pole figure.

plot(sFs1);

%%
% This sector contains one representative from each set of directions
% related by |222| symmetry. Its boundaries therefore remove repeated
% information; they do not crop the definition of the function.

%% Inspect the full symmetrised function
%
% Use |'complete'| when the repetitions themselves matter. The |'upper'|
% option restricts the view to the upper hemisphere.

clf;
plot(sFs1,'complete','upper');

%%
% The smiley motif now occurs in positions related by the half-turns of
% |222| symmetry. All copies have identical values, although their
% positions and orientations on the projection differ.

%% Construct from a function handle
%
% A function handle is convenient when values can be computed for every
% direction. It must accept a <vector3d.vector3d.html |vector3d|> array and
% return one real scalar per direction. Here the directions belong to the
% crystal frame, so the requested point group is crystal symmetry |6/m|.

valueFunction = @(v) 0.1*(v.theta+sin(8*v.x).*sin(8*v.y));
cs = crystalSymmetry('6/m');

%%
% <S2FunHarmonicSym.quadrature.html |quadrature|> computes the harmonic
% coefficients and enforces the supplied symmetry. The |'bandwidth'|
% option keeps spherical harmonic degrees through 16.

sFs2 = S2FunHarmonicSym.quadrature(valueFunction,cs,'bandwidth',16);

clf;
contour(sFs2,'linewidth',2);
mtexColorMap parula

%%
% Only the fundamental sector of |6/m| is drawn. The curved contour lines
% are the part of the scalar function that is not generated by symmetry;
% applying the point group reproduces them over the complete sphere.

%% The maths behind symmetrisation
%
% For a point group $G$, symmetrisation replaces a function $f$ by the
% group average
%
% $$ f_G(\vec v)=\frac{1}{|G|}\sum_{g\in G}f(g\vec v). $$
%
% Applying any group element merely permutes the terms in this sum. The
% result therefore satisfies $f_G(g\vec v)=f_G(\vec v)$ for every $g$ in
% $G$. The harmonic implementation performs this averaging while keeping
% a compact coefficient representation.

close all

%% References
%
% * H.-J. Bunge, _Texture Analysis in Materials Science: Mathematical
% Methods_, Butterworths, 1982, develops the crystal and specimen symmetry
% operations that reduce directional texture information to a
% representative region.

%% Next
%
% Continue with <SO3FunConvolution.html Convolution> to see how a function
% on the rotation group acts on a spherical function.
