%% Importing EBSD Data
%
%% Abstract
% Importing EBSD data in MTEX means to create a <EBSD_index.html EBSD>
% object from data files containing euler angles. Once such an object has
% been created the data can be analyzed and processed in many ways. See e.g.
%
% [[EBSD_index.html,EBSD manipulation]], 
% <EBSD_plot.html plot>, 
% <EBSD_rotate.html rotate>, <EBSD_delete delete>,
%
% Furthermore, such a EBSD object is the starting point to estimate an ODF
% using the command <EBSD_calcODF.html calcODF>.
%
%% Contents
%
%% Inporting EBSD data using the import wizard
%
% The most simplest way to load EBSD data is to use the 
% <matlab:import_wizard('type','EBSD') import wizard>, which 
% can be started either by typing into the command line 

import_wizard; 

%%
% or using from the start menu the item 
% *Start/Toolboxes/MTEX/Import Wizard EBSD* or by clicking on a
% data file and choosing *import* from the context menu. The import
% wizard provides a gui to import data of almost all EBSD data formats
% and to save the imported data as a <EBSD_index.html EBSD> object to the
% workspace or to generate a m-file loading the data automatically.
%
%% Features of the import wizard
%
% * import Euler angles in various conventions
% * import quaternions
% * import EBSD data with weights
% * import multiple phases with multiple crystal symmetries
% * import arbitrary additional data, e.g. MAD, BC, ...
% * specify crystal symmetry by CIF files
% 
%% Importing EBSD data using the method loadEBSD
%
% So far only diffraction data that are stored in a ascii file that consists
% of a table containing in each row the Eule angles of a single orientation
% can be imported using the command <loadEBSD.html loadEBSD>. The general
% syntax as automatically generated by the import wizard is

% specify crystal and specimen symmetry
CS = {...
  symmetry('m-3m'),... % crystal symmetry phase 1
  symmetry('m-3m')};   % crystal symmetry phase 2
SS = symmetry('-1');   % specimen symmetry

% file name
fname = [mtexDataPath '/aachen_ebsd/85_829grad_07_09_06.txt'];

% import ebsd data
ebsd = loadEBSD(fname,CS,SS,'interface','generic',...
  'ColumnNames', { 'Phase' 'x' 'y' 'Euler 1' 'Euler 2' 'Euler 3' 'Mad' 'BC'},...
  'Columns', [2 3 4 5 6 7 8 9],...
  'ignorePhase', 0, 'Bunge');

plot(ebsd,'phase',1)


%% Importing EBSD data from unknown formats
%
% MTEX also provides a way to import data from formats currently not
% directly supported. Therefore you have to read the single orientations
% using standard MATLAB input and output commands. Then you have to call the
% constructor [[EBSD_EBSD.html,EBSD]] with these data to generate a EBSD
% obejct.
%
%% Writing your own interface
%
% Once you have written an interface that reads data from certain data files
% and generates a EBSD object you can integrate this method into MTEX by
% copying it into the folder |MTEX/qta/interfacesEBSD|. Then it will be
% automatical called by the methods loadEBSD. Examples how to write such an
% interface can be found in the directory |MTEX/qta/interfacesEBSD|.
%

