# Runs MATLAB with MTEX in a Docker container, in browser mode
# Requires a .env file (see template.env) with:
#   MATLAB_VERSION=R2025a
#   MTEX_VERSION=6.1.0
#   MLM_LICENSE_FILE=27000@MyServerName
#   MATLAB_DATA=/path/to/your/data
# Usage:
#   docker compose build  # once
#   docker compose up 
#   # go to http://localhost:8888

services:
  mtex-matlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MATLAB_VERSION: ${MATLAB_VERSION}
        MTEX_VERSION: ${MTEX_VERSION}
        MLM_LICENSE_FILE: ${MLM_LICENSE_FILE}
    image: mtex-matlab:${MATLAB_VERSION}-${MTEX_VERSION}
    ports:
      - "8888:8888"
    shm_size: 512M
    environment:
      - MLM_LICENSE_FILE=${MLM_LICENSE_FILE}
    volumes:
      - ${MATLAB_DATA}:/data
    working_dir: /data
    command: -browser
