function [ filter ] = mtexfilefilter( input_args )
%MTEXFILEFILTER Summary of this function goes here
%   Detailed explanation goes here
filter = {'*','All files';...
          '*.exp','Aachen_exp (*.exp)';...
          '*.XPa','BearTex (*.XPa)';...
          '*.cnv','dubna (*.cnv)';...
          '*.cnv','cvnindex (*.cnv)';...
          '*.dat','geesthacht (*.dat)';...
          '*.ptx;*.cpf;*.rpf','heilbronner (*.ptx, *.cpf, *.rpf)';...
          '*.hem','juelich (*.hem)';...
          '*.txt','munich (*.txt)';...
          '*.txt','philips (*.txt)';...
          '*.ptx;*.dat','ptx (*.dat, *.ptx)';...
          '*.PTX','trullenque (*.PTX)'};