function [ sym ] = symmetries( index )
%SYMMETRIES Summary of this function goes here
%   Detailed explanation goes here

sym =  [       {['-1'   ,'            tricline']}; ...
               {['2/m'  ,'          monocline']};...
               {['mmm'  ,'       orthorhombic']};...
               {['4/m'  ,'          tetragonal']};...
               {['4/mmm','     tetragonal']};...
               {['-3'   ,'             trigonal']};...
               {['-3m'  ,'          trigonal']};...
               {['6/m'  ,'          hexagonal']};...
               {['6/mmm','     hexagonal']};...
               {['m-3'  ,'          cubic']};...
               {['m-3m' ,'       cubic']};...
               ];
           
if nargin > 0 
   sym = sym( index );
end