function url = mtexShowDoc(page)
% open a page of the MTEX documentation, installed copy or online
%
% Description
%
% The HTML documentation is generated by makeDoc and ships with a release,
% but doc/html is not part of the repository, and even a local build does not
% contain every page. A link into it then points at a file that is not there
% and clicking it does nothing at all - no page, no message. So a page that
% is not installed is looked up online instead, which keeps the links in the
% command window working for everyone running MTEX from a clone.
%
% Syntax
%
%   mtexShowDoc('EBSDReferenceFrame')
%   url = mtexShowDoc('EBSDReferenceFrame')  % resolve only, do not open
%
% Input
%  page - name of the documentation page, with or without the .html suffix
%
% Output
%  url - where the page was looked up; asking for it opens nothing
%
% See also
% doclink
%

if nargin == 0 || isempty(page), page = 'DocumentationMatlab'; end

if ~(ischar(page) || isStringScalar(page)), page = class(page); end
page = regexprep(char(page),'\.html$','','ignorecase');

local = fullfile(mtex_path,'doc','html',[page '.html']);

isLocal = exist(local,'file') == 2;

if isLocal
  % file:/// wants the path without its leading separator - a posix path
  % brings one of its own, a windows one starts at the drive letter
  url = ['file:///' regexprep(strrep(local,'\','/'),'^/+','')];
else
  url = ['https://mtex-toolbox.github.io/' page '.html'];
end

% asked for the address rather than the page - hand it over and open nothing
if nargout > 0, return; end

if isLocal
  web(url,'-helpbrowser');
else
  % the help browser has nothing to show for a page that is not installed,
  % so send the online copy to the browser the user actually works in
  web(url,'-browser');
end

end
