function make_index(in_dir, out_file)
% append function list to in_dir

% extract class name
class_name = char(regexp(in_dir,'(?<=@)\w*(?=\w*)','match'));
if ~isempty(class_name), class_name = [class_name,'_'];end

functions = helpfunc2struct(in_dir);

contents =  ['%% *Complete function list*',...
             '% <html><table>',...
      strcat('%  <tr>',...
                  '<td width="200px">',...
                    '<a href="', strcat(class_name, {functions.name}) ,'.html">',...
                    {functions.name},'</a></td>',...
                  '<td>', {functions.description},'</td></tr>'),...
             '% </table></html>'];

% append contents to out_file
cell2file(out_file,contents,'a');
